services:
  mikopbx:
    build: .
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    entrypoint: "/sbin/docker-entrypoint"
    volumes:
      - /var/spool/mikopbx/cf:/cf
      - /var/spool/mikopbx/storage:/storage
      - /html/fax:/mikopbx/fax_files
      - ./music:/mikopbx/music
      - ./tools:/tools
    tty: true
    restart: always
    environment:
      # Change the station name through environment variables
      - PBX_NAME=yudejp
      # Change the default SSH port to 23
      - SSH_PORT=23
      # Change the default WEB port to 8080
      - WEB_PORT=8080
      # Change the default WEB HTTPS port to 8443
      - WEB_HTTPS_PORT=8443
